// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqjccmfzkhohfkmvtzdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxamNjbWZ6a2hvaGZrbXZ0emRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzU5MTgsImV4cCI6MjA2NzMxMTkxOH0.xJqyhUk5uwo4mIBGDNJVUEhhux3AXDAvX14d4pvS_OI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});